environment:
  matrix:
    # Disable these while numpy.get_info is broken.
    #- platform: x64
    #  CONDAPATH: C:\Miniconda-x64
    #  PYVER: 2.7

    #- platform: x86
    #  CONDAPATH: C:\Miniconda
    #  PYVER: 2.7

    - platform: x64
      CONDAPATH: C:\Miniconda-x64
      PYVER: 3.5

    - platform: x86
      CONDAPATH: C:\Miniconda
      PYVER: 3.5

build_script:
  - '%CONDAPATH%\Scripts\conda config --set always_yes yes'
  - '%CONDAPATH%\Scripts\conda update conda'
  - '%CONDAPATH%\Scripts\conda create -p C:\pythontest python=%PYVER% numpy scipy nose'
  - '%CONDAPATH%\Scripts\activate C:\pythontest'
  - where python
  - git submodule update --init --recursive
  - python setup.py install

test_script:
  - cd test
  - python solve_random_cone_prob.py
  - nosetests

