matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7.10
  - os: osx
    language: generic
    env: PYTHON=3.4.7
  - os: osx
    language: generic
    env: PYTHON=3.5.1
  - os: osx
    language: generic
    env: PYTHON=3.6.0
  - os: linux 
    language: python 
    python: "2.7"
  - os: linux
    language: python 
    python: "3.4"
  - os: linux
    language: python 
    python: "3.5"
  - os: linux
    language: python 
    python: "3.6"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install liblapack-dev;
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install pyenv-virtualenv gcc;
      pyenv install $PYTHON;
      export PYENV_VERSION=$PYTHON;
      export PATH="/Users/travis/.pyenv/shims:${PATH}";
      pyenv virtualenv testenv;
      python --version;
    fi

install:
  - pip install --upgrade pip
  - pip install numpy scipy nose
  - python setup.py install

script:
  - cd test && nosetests test_scs_basic.py test_scs_rand.py test_scs_sdp.py

notifications:
  email:
    - bodonoghue85@gmail.com

